name: pysumma
channels:
  - conda-forge
dependencies:
  - python>=3.5
  - xarray>=0.11.0
  - pandas
  - jupyterlab=1.*
  - netcdf4>=1.2.5
  - numpy>=1.11.2
  - dask
  - dask-labextension
  - distributed
  - notebook
  - toolz
  - pytest
  - fiona
  - cartopy
  - shapely
  - seaborn
  - matplotlib
  - geopandas
  - traitlets>=4.3.1
  - ipython
  - vdom
  - jupyterlab_launcher
  - pip
  - pip:
    - hs_restclient
